name = "newsnow"
pages_build_output_dir = "dist/output/public"
compatibility_date = "2026-02-24"

[[d1_databases]]
binding = "DB"
database_name = "newsnow_db"
database_id = "d468e144-058e-489c-b3d5-e8874b1f3607"
